# Homework Assignment 2

In [2]:
import numpy as np
import pandas as pd

### Question 1

Create a 4x3 array of letters from `a` through `l` and call it `array1`. Copy the array and call it `array2`, then reshape `array2` to a 6x2 array. Create another copy of the array, called `array3`, and flatten it into a one-dimensional array. Print all three arrays.

In [11]:
array1 = np.array([['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i'], ['j', 'k', 'l']])
array2 = np.copy(array1)
array2 = array2.reshape(6,2)
array3 = np.copy(array1)
array3 = array3.flatten()
print(array1)
print()
print(array2)
print()
print(array3)



[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']
 ['j' 'k' 'l']]

[['a' 'b']
 ['c' 'd']
 ['e' 'f']
 ['g' 'h']
 ['i' 'j']
 ['k' 'l']]

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l']


### Question 2

Create a 3x3 array of integers from 1-9. Calculate the array's row means, then broadcast the row means to subtract them from the original array. (**Note:** the row axis in Python is denoted by `0` while the column axis is denoted by `1`.)

In [10]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m = array1.mean(0)
print(m)
array1 - m.reshape((3, 1))

[4. 5. 6.]


array([[-3., -2., -1.],
       [-1.,  0.,  1.],
       [ 1.,  2.,  3.]])

### Question 3

Using the two arrays provided, first select all rows from `grades` where `students` is either `'Cora'` or `'David'`

In [7]:
students = np.array(['Arthur', 'Betty', 'Cora', 'David', 'Ethan'])
grades = np.array([[95, 80], [72, 78], [85, 85], [87, 92], [82, 88]])
grades[(students == 'Cora') | (students == 'David')]



array([[85, 85],
       [87, 92]])

### Question 4

Use `np.where()` to create a Boolean array that will print `True` when the student's grade is greater than the overall class average (or `mean`) and `False` when it is not.

In [9]:
m = np.mean(grades)

print(np.where(grades > m, 'True', 'False'))


[['True' 'False']
 ['False' 'False']
 ['True' 'True']
 ['True' 'True']
 ['False' 'True']]


### Question 5

Create a 2x4 array of random numbers called `a` using `np.random.randn()` and a 3x4 array of random numbers called `b`. Multiply matrices `a` and `b` together to find the dot product. What is the `shape` of the resulting array? (**Note:** Remember to transpose the arrays as needed!)

In [53]:
a = np.random.randn(2, 4)
b = np.random.randn(3, 4)
c = a.dot(b.T)
c.shape





(2, 3)

### Question 6

Create a Pandas `Series` using the given list of U.S. presidents as the values and the list of election years as the index. Who was elected president in 1876?

In [55]:
year = [1788,1792,1796,1800,1804,1808,1812,1816,1820,1824,1828,1832,1836,1840,1840,1844,1848,1848,1852,1856,1860,1864,1864,1868,1872,1876,1880,1880,1884,1888,1892,1896,1900,1904,1908,1912,1916,1920,1924,1928,1932,1936,1940,1944,1948,1952,1956,1960,1964,1968,1972,1972,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020]
name = ['George Washington','George Washington','John Adams','Thomas Jefferson','Thomas Jefferson','James Madison','James Madison','James Monroe','James Monroe','John Quincy Adams','Andrew Jackson','Andrew Jackson','Martin Van Buren','William Henry Harrison','John Tyler','James K. Polk','Zachary Taylor','Millard Fillmore','Franklin Pierce','James Buchanan','Abraham Lincoln','Abraham Lincoln','Andrew Johnson','Ulysses S. Grant','Ulysses S. Grant','Rutherford B. Hayes','James A. Garfield','Chester A. Arthur','Grover Cleveland','Benjamin Harrison','Grover Cleveland','William McKinley','William McKinley','Theodore Roosevelt','William Howard Taft','Woodrow Wilson','Woodrow Wilson','Warren G. Harding','Calvin Coolidge','Herbert Hoover','Franklin D. Roosevelt','Franklin D. Roosevelt','Franklin D. Roosevelt','Franklin D. Roosevelt','Harry S. Truman','Dwight D. Eisenhower','Dwight D. Eisenhower','John F. Kennedy','Lyndon B. Johnson','Richard Nixon','Richard Nixon','Gerald Ford','Jimmy Carter','Ronald Reagan','Ronald Reagan','George H. W. Bush','Bill Clinton','Bill Clinton','George W. Bush','George W. Bush','Barack Obama','Barack Obama','Donald Trump','Joe Biden']

s = pd.Series(name, index = year)
s[1876]

'Rutherford B. Hayes'

### Question 7

Create a Pandas DataFrame called `df` from the three Series below. Use the Series names as the column names. Slice the DataFrame to see what `party` William Howard Taft belonged to and what `year` he was elected.

In [229]:
year = pd.Series([1788,1792,1796,1800,1804,1808,1812,1816,1820,1824,1828,1832,1836,1840,1840,1844,1848,1848,1852,1856,1860,1864,1864,1868,1872,1876,1880,1880,1884,1888,1892,1896,1900,1904,1908,1912,1916,1920,1924,1928,1932,1936,1940,1944,1948,1952,1956,1960,1964,1968,1972,1972,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020])
name = pd.Series(['George Washington','George Washington','John Adams','Thomas Jefferson','Thomas Jefferson','James Madison','James Madison','James Monroe','James Monroe','John Quincy Adams','Andrew Jackson','Andrew Jackson','Martin Van Buren','William Henry Harrison','John Tyler','James K. Polk','Zachary Taylor','Millard Fillmore','Franklin Pierce','James Buchanan','Abraham Lincoln','Abraham Lincoln','Andrew Johnson','Ulysses S. Grant','Ulysses S. Grant','Rutherford B. Hayes','James A. Garfield','Chester A. Arthur','Grover Cleveland','Benjamin Harrison','Grover Cleveland','William McKinley','William McKinley','Theodore Roosevelt','William Howard Taft','Woodrow Wilson','Woodrow Wilson','Warren G. Harding','Calvin Coolidge','Herbert Hoover','Franklin D. Roosevelt','Franklin D. Roosevelt','Franklin D. Roosevelt','Franklin D. Roosevelt','Harry S. Truman','Dwight D. Eisenhower','Dwight D. Eisenhower','John F. Kennedy','Lyndon B. Johnson','Richard Nixon','Richard Nixon','Gerald Ford','Jimmy Carter','Ronald Reagan','Ronald Reagan','George H. W. Bush','Bill Clinton','Bill Clinton','George W. Bush','George W. Bush','Barack Obama','Barack Obama','Donald Trump','Joe Biden'])
party = pd.Series(['Unaffiliated','Unaffiliated','Federalist','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic-Republican','Democratic','Democratic','Democratic','Whig','Whig','Democratic','Whig','Whig','Democratic','Democratic','Republican','National Union','Democratic','Republican','Republican','Republican','Republican','Republican','Democratic','Republican','Democratic','Republican','Republican','Republican','Republican','Democratic','Democratic','Republican','Republican','Republican','Democratic','Democratic','Democratic','Democratic','Democratic','Republican','Republican','Democratic','Democratic','Republican','Republican','Republican','Democratic','Republican','Republican','Republican','Democratic','Democratic','Republican','Republican','Democratic','Democratic','Republican','Democratic'])
number = pd.Series([1,1,2,3,3,4,4,5,5,6,7,7,8,9,10,11,12,13,14,15,16,16,17,18,18,19,20,21,22,23,24,25,25,26,27,28,28,29,30,31,32,32,32,32,33,34,34,35,36,37,37,38,39,40,40,41,42,42,43,43,44,44,45,46])

df = pd.DataFrame({'year' : year, 'name' : name, 'party': party, 'number': number})
df[df['name'] == 'William Howard Taft']

year                 name       party  number
34  1908  William Howard Taft  Republican      27

### Question 8

Using the DataFrame you created in the question before, `set_index` to the `year` column if you have not already done this. Slice the DataFrame using `.loc` to show all those who were president from 1900-1920.

In [190]:
df = df.set_index(year)
df.loc[(df['year']> 1900) & (df['year'] <= 1920)]


        
        
        
        





year                 name       party  number
1904  1904   Theodore Roosevelt  Republican      26
1908  1908  William Howard Taft  Republican      27
1912  1912       Woodrow Wilson  Democratic      28
1916  1916       Woodrow Wilson  Democratic      28
1920  1920    Warren G. Harding  Republican      29

### Question 9

Filter the DataFrame you created in Question 7 to see how many `'Democratic'` and how many `'Republican'` presidents we have had. Use the `.count()` method to count the number of rows in each category and `print` the name of the party along with the result.

In [230]:
Democratic = df[df['party'] == 'Democratic']
print ('Democratic', Democratic.count())
print()
Republican = df[df['party'] == 'Republican']
print ('Republican', Republican.count())
print()



Democratic year      24
name      24
party     24
number    24
dtype: int64

Republican year      25
name      25
party     25
number    25
dtype: int64



### Question 10

`Map` a `lambda` function onto the `'name'` column to capitalize all the president names in the DataFrame you created in Question 7. Remember to apply the `.upper()` method to capitalize the letters.

In [228]:
df['name'].map(lambda cap: cap.upper())  

0     GEORGE WASHINGTON
1     GEORGE WASHINGTON
2            JOHN ADAMS
3      THOMAS JEFFERSON
4      THOMAS JEFFERSON
            ...        
59       GEORGE W. BUSH
60         BARACK OBAMA
61         BARACK OBAMA
62         DONALD TRUMP
63            JOE BIDEN
Name: name, Length: 64, dtype: object